### PR TITLE
Align layout with our intranet styling

### PR DESCRIPTION
**Pull request by MarcelMue**
Screenshot 2023-03-03 at 08 35 02

Just cleaning up the layout. Doesn't look pretty but better than before.

### CODE REVIEW

**Review by ubergesundheit — CHANGES_REQUESTED** [review]
please shrink + compress the image for the sake of the environment

hint: https://squoosh.app

**Comment by MarcelMue** [comment]
> please shrink + compress the image for the sake of the environment
> 
> hint: https://squoosh.app

I did compress it - how would you want me to shrink it? I took the OG image from our intranet, so we should do the same there?

**Comment by ubergesundheit** [comment]
> I did compress it - how would you want me to shrink it? I took the OG image from our intranet, so we should do the same there?

Not sure.. something reasonable like ~2000 pixel in width?

Compressing in the intranet repo does not make sense at this point in time. Its already on the main branch thus shrinking would require to rewrite the history to shrink (I think)

Here we can make sure the compressed and shrinked image is merged into main :)

**Comment by MarcelMue** [comment]
> > I did compress it - how would you want me to shrink it? I took the OG image from our intranet, so we should do the same there?
> 
> Not sure.. something reasonable like ~2000 pixel in width?
> 
> Compressing in the intranet repo does not make sense at this point in time. Its already on the main branch thus shrinking would require to rewrite the history to shrink (I think)
> 
> Here we can make sure the compressed and shrinked image is merged into main :)

Done :+1:

**Review by ubergesundheit — APPROVED** [review]
cool thanks

**Pull request merged**
