### PR TITLE
add more logql metrics queries

### PR DESCRIPTION
**Pull request by TheoBrigitte**
This PR does add more LogQL metrics queries examples.

### CODE REVIEW

**Review by hervenicol — COMMENTED** [review]
I think these queries are heavy and slow. Maybe a small warning would be nice.
Also, build does not pass :shrug:

**Comment by lyind** [comment]
Regarding the failed build:
`Check Markdown links / Broken Links (push)`: can be ignored (fails due links becoming unavailable externally)
`ci/circleci: build`: I retried and that fixed the sporadic issues (failure to push image)

**Comment by TheoBrigitte** [comment]
@hervenicol I added a heavy query warning.

**Review by hervenicol — APPROVED** [review]
Fine with me

**Comment by QuentinBisson** [comment]
@TheoBrigitte can you merge ? :)

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
